### ISSUE TITLE
Button release event

### ISSUE THREAD

**Issue by jamieleepreece** [ArunMichaelDsouza/joypad.js#15]
Is there plans for a button release event? Currently I can only hook into the button press event.

**Comment by jamieleepreece** [comment]
Added a PR #16

**Comment by ArunMichaelDsouza** [comment]
Button release event is now available in [v2.3.2](https://github.com/ArunMichaelDsouza/joypad.js/releases/tag/v2.3.2). Thanks again for the PR!
