### ISSUE TITLE
"ReferenceError: window is not defined" when using server-side rendering

### ISSUE THREAD

**Issue by silentstormm** [ArunMichaelDsouza/joypad.js#2]
When I run `node app.js` it throws the following error:

    [...]\node_modules\joypad.js\dist\joypad.min.js:6 
    !function(t){var e={};function n(o){if(e[o])return e[o].exports;var i=e[o]={i:o,l:!1,exports:{}};return t[o].call(i.exports,i,i.exports,n),i.l=!0,i.exports}n.m=t,n.c=e,n.d=function(t,e,o){n.o(t,e)||Object.defineProperty(t,e,{enumerable:!0,get:o})},n.r=function(t){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(t,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(t,"__esModule",{value:!0})},n.t=function(t,e){if(1&e&&(t=n(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var i in t)n.d(o,i,function(e){return t[e]}.bind(null,i));return o},n.n=function(t){var e=t&&t.__esModule?function(){return t.default}:function(){return t};return n.d(e,"a",e),e},n.o=function(t,e){return Object.prototype.hasOwnProperty.call(t,e)},n.p="",n(n.s=0)}([function(t,e,n){"use s
    
    ReferenceError: window is not defined
        at Module.<anonymous> 
        ([...]\node_modules\joypad.js\dist\joypad.min.js:6:4385)
        at n ([...]\node_modules\joypad.js\dist\joypad.min.js:6:110)
        at [...]\node_modules\joypad.js\dist\joypad.min.js:6:902
        at Object.<anonymous> ([...]\node_modules\joypad.js\dist\joypad.min.js:6:911)
        at Module._compile (internal/modules/cjs/loader.js:1128:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
        at Module.load (internal/modules/cjs/loader.js:983:32)
        at Function.Module._load (internal/modules/cjs/loader.js:891:14)
        at Module.require (internal/modules/cjs/loader.js:1023:19)
        at require (internal/modules/cjs/helpers.js:72:18)

**Comment by ArunMichaelDsouza** [comment]
Hi @SilentStormm, I believe you might be using the library in a server environment where there is no window object. Which is why this error is thrown. joypad.js is a browser-only library.

**Comment by silentstormm** [comment]
I might be misunderstanding your answer, but I'm trying to run joypad.js in a web app that uses a node.js server.

I also only included the library and didn't use it when the error occurred.

**Comment by ArunMichaelDsouza** [comment]
Can you please let me know how you are importing the library?

**Comment by silentstormm** [comment]
I assumed I could import it by `const joypad = require("joypad.js")` after installing it with npm, as with most Node.js libraries.

**Comment by ArunMichaelDsouza** [comment]
Yes, that is correct. What I think is that the library is being imported and bundled in a non-browser environment where the ``window`` object is not found. Can you please confirm whether you are trying to import it in a server-side script or maybe in an electron app?

**Comment by silentstormm** [comment]
Ah, that is indeed the issue and I'm just being an idiot. Thanks!
