### ISSUE TITLE
Feature Request: Event Emulation

### ISSUE THREAD

**Issue by uplusion23** [ArunMichaelDsouza/joypad.js#5]
When using this library I am sometimes away from the house where I do not have a gamepad to test functions, would it be possible to get a `joypad.trigger('event', 'button_1');` feature? 

Thanks!

**Comment by ArunMichaelDsouza** [comment]
Hi @uplusion23,

This can certainly be achieved by publishing the required event and passing in the custom data for that event. We can have a ``trigger`` method in [joypad.js](https://github.com/ArunMichaelDsouza/joypad.js/blob/master/src/joypad.js) -

```
trigger: function(event, data) {
    return emitter.publish(event, data);
},
```
This would simply emit the provided event with the data and can be used like this - 

```
joypad.trigger('button_press', {
    detail: {
        buttonName: 'button_0'
    }
});
```

If you have the time then I would really appreciate a PR for this. Thanks!
